[[snippets]]
prefix = "plugin"
scope = ["rust"]
body = '''use bevy::prelude::*;

pub(super) fn plugin(app: &mut App) {
	$1
}'''
description = "Bevy: New top-level function Plugin"

[[snippets]]
prefix = "component"
scope = ["rust"]
body = '''#[derive(Component, Reflect, Debug)]
#[reflect(Component)]
pub struct $1;'''
description = "Bevy: New Component"

[[snippets]]
prefix = "bundle"
scope = ["rust"]
body = '''pub fn $1($0) -> impl Bundle {
  
}'''
description = "Bevy: New Entity function"

[[snippets]]
prefix = "resource"
scope = ["rust"]
body = '''#[derive(Resource, Reflect, Debug, Default)]
#[reflect(Resource)]
pub struct $1;'''
description = "Bevy: New Resource"

[[snippets]]
prefix = "assets"
scope = ["rust"]
body = '''#[derive(Resource, Asset, Clone, Reflect)]
#[reflect(Resource)]
pub struct $1 {
	#[dependency]
	$0
}

impl FromWorld for $1 {
    fn from_world(world: &mut World) -> Self {
        let assets = world.resource::<AssetServer>();

        Self {
				  
        }
    }
}'''
description = "Bevy: New Assets Resource"

[[snippets]]
prefix = "event"
scope = ["rust"]
body = '''#[derive(Event, Debug)]
pub struct $1;'''
description = "Bevy: New Event"

[[snippets]]
prefix = "message"
scope = ["rust"]
body = '''#[derive(Message, Debug)]
pub struct $1;'''
description = "Bevy: New Message"

[[snippets]]
prefix = "systemset"
scope = ["rust"]
body = '''#[derive(SystemSet, Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum $1 {
	$0
}'''
description = "Bevy: New SystemSet"

[[snippets]]
prefix = "schedule"
scope = ["rust"]
body = '''#[derive(ScheduleLabel, Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub struct $1;'''
description = "Bevy: New Schedule"

[[snippets]]
prefix = "states"
scope = ["rust"]
body = '''#[derive(States, Copy, Clone, Eq, PartialEq, Hash, Debug, Default)]
pub enum $1 {
	#[default]
	$0
}'''
description = "Bevy: New States"

[[snippets]]
prefix = "testmod"
scope = ["rust"]
body = '''#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_$1() {
		$0
	}
}'''
description = "Rust: Test module with test function"

[[snippets]]
prefix = "test"
scope = ["rust"]
body = '''#[test]
fn test_$1() {
	$0
}'''
description = "Rust: Test function"
